Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-01, with the labels that each got.

#15 Fix HOME env var setup when unset
  Makefile
Labels: approved

#17 MIXEDARCH-325: Add flags to enable a subset of the controllers
  config/default/default/manager_auth_proxy_patch.yaml
  main.go
Labels: approved, lgtm, jira/valid-reference

#19 Improve logging
  config/default/default/manager_auth_proxy_patch.yaml
  controllers/podplacement/image_config.go
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_reconciler.go
Labels: approved, lgtm

#25 MIXEDARCH-352: Updates README.md
  README.md
Labels: jira/valid-reference

#28 Fixed yaml in README
  README.md
Labels: approved, lgtm
