Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-05, with the labels that each got.

#93 MULTIARCH-4547: Add labels, annotations, reconcile konflux and other konflux-related fixes
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle.konflux.Dockerfile
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/bases/multiarch-tuning-operator.clusterserviceversion.yaml
  controllers/operator/objects.go
  hack/golangci-lint.sh
  hack/gosec.sh
  hack/patch-bundle-dockerfile.sh
  konflux.Dockerfile
Labels: approved, do-not-merge/hold, jira/valid-reference

#94 [KFLUX] Update operator ref in the bundle
  bundle.konflux.Dockerfile
Labels: approved, lgtm

#95 Enable konflux prefetch
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
Labels: approved, lgtm

#79 Create e2e for namespaceSelector
  pkg/e2e/operator/e2e_test.go
  pkg/e2e/operator/pod_placement_config_test.go
Labels: approved, lgtm

#99 Update bundle.konflux.Dockerfile
  bundle.konflux.Dockerfile
Labels: approved, lgtm

#97 Revert "[REVERT-ME] Use els as a base for the bundle" and "use rhel:9.2-1222 to overcome CDN/signature issues"
  bundle.konflux.Dockerfile
  konflux.Dockerfile
Labels: approved, lgtm

#105 Pin operator image in the bundle from multiarch-tuning-operator-bzdhk
  bundle.konflux.Dockerfile
Labels: approved, lgtm

#102 Add e2e for image pull secrets
  pkg/e2e/podplacement/e2e_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/builder/secret_builder.go
Labels: approved, lgtm

#107 Add schedulingGate Label verify
  pkg/e2e/const.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/pod_placement_test.go
Labels: approved, lgtm

#108 :warning: Rename PodPlacementConfig to ClusterPodPlacementConfig
  PROJECT
  README.md
  apis/multiarch/v1alpha1/clusterpodplacementconfig_types.go
  apis/multiarch/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  bundle/manifests/multiarch.openshift.io_clusterpodplacementconfigs.yaml
  config/crd/bases/multiarch.openshift.io_clusterpodplacementconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_multiarch_clusterpodplacementconfigs.yaml
  config/crd/patches/webhook_in_multiarch_clusterpodplacementconfigs.yaml
  config/manifests/bases/multiarch-tuning-operator.clusterserviceversion.yaml
  config/rbac/multiarch_clusterpodplacementconfig_editor_role.yaml
  config/rbac/multiarch_clusterpodplacementconfig_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/multiarch_v1alpha1_clusterpodplacementconfig.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/clusterpodplacementconfig_controller_test.go
  controllers/operator/objects.go
  controllers/operator/suite_test.go
  main.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/e2e_test.go
Labels: approved, lgtm

#112 OCPBUGS-33008: do not add scheduling gates to pods with nodeName set …
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  controllers/podplacement/scheduling_gate_mutating_webhook_test.go
  pkg/testing/builder/pod_builder.go
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#115 MULTIARCH-4635: Re-enable hermetic builds
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
  bundle.konflux.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#121 MULTIARCH-4315: Implements workloads partitioning annotations
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/objects.go
  hack/deploy-and-e2e.sh
Labels: approved, lgtm, jira/valid-reference

#117 MULTIARCH-4598: Use a single service account for operator and operands
  bundle/manifests/multiarch-tuning-operator-image-registry-certificates-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/multiarch-tuning-operator-image-registry-certificates-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-controller_v1_serviceaccount.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-webhook-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-webhook-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/multiarch-tuning-operator-podplacement-webhook_v1_serviceaccount.yaml
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/podplacement/kustomization.yaml
  config/podplacement/openshift_image_registry_cluster_role.yaml
  config/podplacement/openshift_image_registry_cluster_role_binding.yaml
  config/podplacement/podplacement_controller_role.yaml
  config/podplacement/podplacement_controller_role_binding.yaml
  config/podplacement/podplacement_controller_service_account.yaml
  config/podplacement/podplacement_leader_election_role_binding.yaml
  config/podplacement/podplacement_webhook_role.yaml
  config/podplacement/podplacement_webhook_role_binding.yaml
  config/podplacement/podplacement_webhook_service_account.yaml
  config/rbac/role.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/objects.go
  controllers/podplacement/pod_reconciler.go
  pkg/systemconfig/syncer.go
Labels: approved, lgtm, jira/valid-reference
