Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-08, with the labels that each got.

#183 MULTIARCH-4704: Upadate tekton branch name
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
Labels: approved, lgtm, jira/valid-reference

#205 MULTIARCH-4933: Do not disable operands deletion
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/manifests/bases/multiarch-tuning-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#208 MULTIARCH-4936: Send events to the Pods to better inform about the actions of the scheduling gate
  controllers/podplacement/events.go
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/pod_reconciler.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  controllers/podplacement/suite_test.go
  go.mod
  go.sum
  main.go
  vendor/github.com/panjf2000/ants/v2/.gitignore
  vendor/github.com/panjf2000/ants/v2/CODE_OF_CONDUCT.md
  vendor/github.com/panjf2000/ants/v2/CONTRIBUTING.md
  vendor/github.com/panjf2000/ants/v2/LICENSE
  vendor/github.com/panjf2000/ants/v2/README.md
  vendor/github.com/panjf2000/ants/v2/README_ZH.md
  vendor/github.com/panjf2000/ants/v2/ants.go
  vendor/github.com/panjf2000/ants/v2/internal/sync/spinlock.go
  vendor/github.com/panjf2000/ants/v2/multipool.go
  vendor/github.com/panjf2000/ants/v2/multipool_func.go
  vendor/github.com/panjf2000/ants/v2/options.go
  vendor/github.com/panjf2000/ants/v2/pool.go
  vendor/github.com/panjf2000/ants/v2/pool_func.go
  vendor/github.com/panjf2000/ants/v2/worker.go
  vendor/github.com/panjf2000/ants/v2/worker_func.go
  vendor/github.com/panjf2000/ants/v2/worker_loop_queue.go
  vendor/github.com/panjf2000/ants/v2/worker_queue.go
  vendor/github.com/panjf2000/ants/v2/worker_stack.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#207 MULTIARCH-4934: ordered removal of the operand and minor fixes
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/role.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/clusterpodplacementconfig_controller_test.go
  controllers/operator/objects.go
  controllers/operator/suite_test.go
  controllers/podplacement/events.go
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/pod_reconciler.go
  controllers/podplacement/pod_reconciler_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  main.go
  pkg/utils/const.go
  pkg/utils/resource.go
  pkg/utils/runtime.go
Labels: approved, lgtm, jira/valid-reference

#204 MULTIARCH-4812: exclude pods in namespaces that are pinned to the control plane
  controllers/operator/objects.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/utils/const.go
  pkg/utils/utils.go
Labels: approved, lgtm, jira/valid-reference

#216 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
Labels: needs-ok-to-test

#214 MULTIARCH-4937: Implement Status of the ClusterPodPlacementConfig, conditions and improve reliability.
  apis/multiarch/v1beta1/clusterpodplacementconfig_types.go
  apis/multiarch/v1beta1/clusterpodplacementconfig_types_test.go
  apis/multiarch/v1beta1/clusterpodplacementconfig_webhook.go
  apis/multiarch/v1beta1/conditions.go
  bundle/manifests/multiarch.openshift.io_clusterpodplacementconfigs.yaml
  config/crd/bases/multiarch.openshift.io_clusterpodplacementconfigs.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/clusterpodplacementconfig_controller_test.go
  controllers/operator/objects.go
  pkg/e2e/operator/e2e_test.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/e2e_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/builder/cluster_role_binding_builder.go
  pkg/testing/builder/clusterpodplacementconfig_builder.go
  pkg/testing/builder/deployment_builder.go
  pkg/testing/builder/mutating_webhook_configuration_builder.go
  pkg/testing/builder/service_builder.go
  pkg/testing/framework/cluster_pod_placement_config.go
  pkg/testing/registry/registry.go
  pkg/utils/const.go
Labels: approved, lgtm, jira/valid-reference

#222 OCPBUGS-38601: The operand should not fail when the operator is uninstalled without prior deletion of the operator
  apis/multiarch/v1beta1/groupversion_info.go
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/clusterpodplacementconfig_controller_test.go
  controllers/operator/objects.go
  pkg/testing/builder/cluster_role_builder.go
  pkg/testing/builder/role_binding_builder.go
  pkg/testing/builder/role_builder.go
  pkg/testing/builder/service_account_builder.go
  pkg/testing/framework/cluster_pod_placement_config.go
  pkg/utils/const.go
  pkg/utils/resource.go
Labels: approved, jira/valid-bug, lgtm, jira/severity-moderate, jira/valid-reference

#228 Mount the nodes' /etc/containers/ and /etc/docker/
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/objects.go
  controllers/podplacement/suite_test.go
  main.go
  pkg/systemconfig/types.go
Labels: approved, lgtm

#234 Update build_root_image
  .ci-operator.yaml
  hack/deploy-and-e2e.sh
Labels: approved, lgtm

#226 MULTIARCH-4964: Update refs to 1.0.0 and add version makefile target
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle.konflux.Dockerfile
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/manifests/bases/multiarch-tuning-operator.clusterserviceversion.yaml
  deploy/base/operators.coreos.com/subscriptions/openshift-multiarch-tuning-operator/subscription.yaml
  docs/ocp-release.md
  hack/bump-version.sh
  hack/patch-bundle-dockerfile.sh
  konflux.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#240 NO-JIRA: Add securityContext to kube-rbac-proxy containers
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/objects.go
  hack/deploy-and-e2e.sh
Labels: approved, lgtm, jira/valid-reference

#246 OCPBUGS-36244: Cluster wide proxy
  bundle/manifests/multiarch-tuning-operator-trusted-ca_v1_configmap.yaml
  config/manager/custom_ca_certificate.yaml
  config/manager/kustomization.yaml
  controllers/operator/objects.go
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference
