Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-03, with the labels that each got.

#44 MIXEDARCH-442: Add test for nodeAffinity conflict or non conflict
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/pod_reconciler_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/builder/cluster_role_binding_builder.go
  pkg/testing/builder/container_builder.go
  pkg/testing/builder/deployment_builder.go
  pkg/testing/builder/node_selector_requirement_builder.go
  pkg/testing/builder/node_selector_term_builder.go
  pkg/testing/builder/pod_builder.go
  pkg/testing/builder/pod_spec_builder.go
  pkg/testing/builder/security_context_builder.go
  pkg/testing/builder/subject_builder.go
  pkg/testing/builder/volume_builder.go
  pkg/testing/builder/volume_mount_builder.go
  pkg/utils/const.go
  test/manifests/08-example-node-selector.yaml
  test/manifests/09-example-multiple-affinity.yaml
Labels: approved, lgtm, jira/valid-reference

#52 MULTIARCH-4171: Multiarch builds w/ Konflux
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
  bundle.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#47 Removed temporary <1.29 bug workaround for nil affinity
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  pkg/e2e/podplacement/pod_placement_test.go
Labels: approved, lgtm

#58 Fix gomod
  Makefile
  go.mod
  go.sum
Labels: approved
