Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-11, with the labels that each got.

#346 MULTIARCH-4973: Add more log printing
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/framework/pod.go
  pkg/testing/registry/registry.go
Labels: approved, lgtm, jira/valid-reference

#355 Fix failing Konflux tests
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
Labels: approved, lgtm

#364 OCPBUGS-44703: Invalidate registry cache before inspection of pods
  pkg/image/inspector.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#365 Verify signature only for the single manifest image, not for the top level manifest
  pkg/image/inspector.go
Labels: approved, lgtm

#367 Adding automerging for konflux prs that update tekton
  renovate.json
Labels: lgtm
