Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-09, with the labels that each got.

#248 Remove sbom-json-check
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
Labels: approved, lgtm

#255 MULTIARCH-4877: Advertise the operator as supporting disconnected sce…
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/manifests/bases/multiarch-tuning-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#256 OCPBUGS-38823: skip bundle images when computing the set of compatible architectures for a given pod
  controllers/podplacement/pod_reconciler_test.go
  pkg/image/inspector.go
  pkg/testing/framework/node_affinity_equivalence_matcher.go
  pkg/testing/image/fake/registry/mock_image.go
  pkg/testing/image/fake/registry/seed.go
  pkg/utils/const.go
Labels: approved, jira/valid-bug, lgtm, jira/severity-critical, jira/valid-reference

#262 Update multiarch-tuning-operator to 98da044
  bundle.konflux.Dockerfile
Labels: approved, lgtm

#193 MULTIARCH-4309: Add test for ITMS
  hack/ci-test.sh
  hack/deploy-and-e2e.sh
  pkg/e2e/const.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/e2e_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/builder/image_content_source_policy.go
  pkg/testing/builder/image_digest_mirror.go
  pkg/testing/builder/image_digest_mirror_set.go
  pkg/testing/builder/image_tag_mirror.go
  pkg/testing/builder/image_tag_mirror_set.go
  pkg/testing/builder/ingress_builder.go
  pkg/testing/builder/ingress_rule_builder.go
  pkg/testing/builder/ingress_rule_path_builder.go
  pkg/testing/builder/repository_digest_mirror.go
  pkg/testing/framework/cluster_operator.go
  pkg/testing/framework/image_config.go
  pkg/testing/framework/machineconfig.go
  pkg/testing/framework/pod.go
  pkg/testing/framework/utils.go
  pkg/testing/registry/registry.go
Labels: approved, lgtm, jira/valid-reference

#273 NO-JIRA: Do not build a multiarch bundle
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
Labels: approved, lgtm, jira/valid-reference

#272 MULTIARCH-4296: Add more pre-checking logic in the webhook to skip pods that will not get a patched nodeAffinity
  controllers/podplacement/events.go
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/pod_reconciler.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/utils/const.go
  pkg/utils/utils.go
Labels: approved, lgtm, jira/valid-reference

#286 fix path env variable in deploy-and-e2e.sh
  hack/deploy-and-e2e.sh
  pkg/e2e/podplacement/e2e_test.go
Labels: approved, lgtm

#280 OCPBUGS-42240: Refine security context
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/operator/objects.go
Labels: approved, jira/valid-bug, lgtm, jira/severity-important, jira/valid-reference

#287 MULTIARCH-4565: Run integration tests in Konflux
  .tekton/multiarch-tuning-operator-integration-tests.yaml
Labels: approved, lgtm, jira/valid-reference

#282 MULTIARCH-5000: Refine log levels
  apis/multiarch/common/verbositylevel.go
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/podplacement/image_config.go
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_reconciler.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  main.go
  pkg/image/inspector.go
Labels: approved, lgtm, jira/valid-reference

#293 Debug info when the deployment of the operator fails and minor fixes
  hack/ci-test.sh
  hack/deploy-and-e2e.sh
Labels: approved, lgtm

#295 MULTIARCH-4257: Alerts
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/clusterpodplacementconfig_controller.go
  controllers/operator/objects.go
  docs/alerts/pod-placement-controller-down.md
  docs/alerts/pod-placement-webhook-down.md
  pkg/utils/resource.go
Labels: approved, lgtm, jira/valid-reference

#279 Add LRU cache with expirable keys
  controllers/podplacement/metrics/common_metrics.go
  controllers/podplacement/metrics/controller.go
  controllers/podplacement/metrics/utils.go
  controllers/podplacement/metrics/webhook.go
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_reconciler.go
  controllers/podplacement/pod_reconciler_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  go.mod
  pkg/image/cache.go
  pkg/image/facade.go
  pkg/image/inspector.go
  pkg/image/metrics/common_metrics.go
  pkg/testing/image/fake/cache.go
  pkg/testing/image/fake/facade.go
  pkg/testing/image/fake/registry/mock_image.go
  pkg/testing/image/fake/registry/seed.go
  pkg/utils/utils.go
  vendor/github.com/hashicorp/golang-lru/v2/expirable/expirable_lru.go
  vendor/modules.txt
Labels: approved, lgtm

#298 MULTIARCH-5029: Explicitly set AutomountServiceAccountToken in pod specs and disable it by default in the service account specs
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/operator/objects.go
Labels: approved, lgtm, jira/valid-reference
