Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2024-10, with the labels that each got.

#299 MULTIARCH-5023: Refine mem file for auth
  pkg/image/inspector.go
Labels: approved, lgtm, jira/valid-reference

#296 Revert 8928d81e5d: Extract the single-arch manifest from the bundle to allow extraction on arm64 nodes
  hack/deploy-and-e2e.sh
Labels: approved, lgtm

#303 [MINOR] Fix copied/pasted comment on Makefile
  Makefile
Labels: approved, lgtm

#306 MULTIARCH-4965: snapshots multiarch-tuning-operator-1-0-jwfr7
  catalog/multiarch-tuning-operator/index.yaml
Labels: approved, lgtm, jira/valid-reference

#307 MULTIARCH-4965: snapshots multiarch-tuning-operator-1-0-jwfr7
  catalog/multiarch-tuning-operator/index.yaml
Labels: approved, lgtm, jira/valid-reference

#319 Pivot 1.0.0 to snapshots/multiarch-tuning-operator-1-0-jwfr7
  catalog/multiarch-tuning-operator/index.yaml
Labels: approved, lgtm

#318 MULTIARCH-4307: Add fix for e2e running in cluster-wide proxy based cluster
  pkg/testing/builder/configmap_builder.go
  pkg/testing/builder/volume_builder.go
  pkg/testing/builder/volume_mount_builder.go
  pkg/testing/registry/registry.go
Labels: approved, lgtm, jira/valid-reference

#330 OCPBUGS-42165: Do not cache images from containers with image pull policy 'Always'
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/pod_reconciler_test.go
  pkg/image/cache.go
  pkg/image/facade.go
  pkg/image/inspector.go
  pkg/image/interfaces.go
  pkg/testing/builder/pod_builder.go
  pkg/testing/image/fake/cache.go
  pkg/testing/image/fake/facade.go
  pkg/testing/image/fake/inspector.go
  pkg/testing/image/fake/registry/mock_image.go
  pkg/testing/image/fake/registry/seed.go
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#335 OCPBUGS-41554: remove cluster-ca.crt and kube-root-ca.crt from operator
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/operator/objects.go
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#339 MULTIARCH-4973: change all the builders to build pointers
  controllers/operator/clusterpodplacementconfig_controller_test.go
  controllers/podplacement/pod_model_test.go
  controllers/podplacement/pod_reconciler_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook_test.go
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/builder/build.go
  pkg/testing/builder/cluster_role.go
  pkg/testing/builder/cluster_role_binding.go
  pkg/testing/builder/clusterpodplacementconfig.go
  pkg/testing/builder/configmap.go
  pkg/testing/builder/container.go
  pkg/testing/builder/container_env.go
  pkg/testing/builder/daemonset.go
  pkg/testing/builder/deployment.go
  pkg/testing/builder/deployment_config.go
  pkg/testing/builder/job.go
  pkg/testing/builder/mutating_webhook_configuration.go
  pkg/testing/builder/node_selector_requirement.go
  pkg/testing/builder/node_selector_term.go
  pkg/testing/builder/pod.go
  pkg/testing/builder/pod_spec.go
  pkg/testing/builder/role.go
  pkg/testing/builder/role_binding.go
  pkg/testing/builder/secret.go
  pkg/testing/builder/security_context.go
  pkg/testing/builder/service.go
  pkg/testing/builder/service_account.go
  pkg/testing/builder/service_port.go
  pkg/testing/builder/statefulset.go
  pkg/testing/builder/subject.go
  pkg/testing/builder/volume.go
  pkg/testing/builder/volume_mount.go
  pkg/testing/registry/registry.go
Labels: approved, lgtm, jira/valid-reference
