Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2025-01, with the labels that each got.

#384 MULTIARCH-5056: cache the ClusterPodPlacementConfig using informers
  apis/multiarch/v1beta1/groupversion_info.go
  controllers/operator/clusterpodplacementconfig_controller_test.go
  controllers/operator/suite_test.go
  controllers/podplacement/clusterpodplacementconfg_informer.go
  main.go
  pkg/informers/cache.go
  pkg/informers/interfaces.go
Labels: approved, lgtm, jira/valid-reference

#416 Move enhancement to repo
  docs/enhancements/MTO-0001.md
Labels: approved, lgtm

#414 Konflux Remove JAVA_COMMUNITY_DEPENDENCIES
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
Labels: approved, lgtm

#427 OCPBUGS-45885: ignore pods owned by DaemonSet
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_model_test.go
  pkg/e2e/podplacement/pod_placement_test.go
  pkg/testing/builder/owner_reference.go
  pkg/testing/builder/pod.go
  pkg/testing/framework/pod.go
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#424 changing the test suite run cases concurrently
  controllers/operator/suite_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  controllers/podplacement/suite_test.go
  hack/ci-test.sh
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/e2e_test.go
  pkg/e2e/suites_lifecycle.go
  pkg/systemconfig/types.go
  pkg/testing/framework/utils.go
  pkg/testing/image/fake/registry/registry.go
Labels: approved, lgtm

#434 Revert "changing the test suite run cases concurrently"
  controllers/operator/suite_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
  controllers/podplacement/suite_test.go
  hack/ci-test.sh
  pkg/e2e/operator/pod_placement_config_test.go
  pkg/e2e/podplacement/e2e_test.go
  pkg/e2e/suites_lifecycle.go
  pkg/systemconfig/types.go
  pkg/testing/framework/utils.go
  pkg/testing/image/fake/registry/registry.go
Labels: approved, lgtm

#354 MULTIARCH-5031: Remove extra code
  bundle/manifests/multiarch-tuning-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/objects.go
  controllers/podplacement/image_config.go
  controllers/podplacement/image_content_source_policy.go
  controllers/podplacement/image_digest_mirror_set.go
  controllers/podplacement/image_tag_mirror_set.go
  controllers/podplacement/registry_certificates.go
  controllers/podplacement/suite_test.go
  controllers/podplacement/system_config.go
  main.go
  pkg/image/inspector.go
  pkg/image/systemconfig.go
  pkg/systemconfig/interfaces.go
  pkg/systemconfig/syncer.go
  pkg/systemconfig/types.go
Labels: approved, lgtm, jira/valid-reference
