Repository outrigger-project/multiarch-tuning-operator, pull requests merged in 2025-04, with the labels that each got.

#563 Disable renovate auto go module updates
  renovate.json
Labels: lgtm

#565 MULTIARCH-5336: disable dockerfile updates through renovate
  renovate.json
Labels: approved, lgtm, jira/valid-reference

#525 MULTIARCH-5363: add logic to check if the preferred node affinity has already been set as to not overwrite it
  controllers/podplacement/pod_model.go
  controllers/podplacement/pod_reconciler.go
  controllers/podplacement/pod_reconciler_test.go
  controllers/podplacement/scheduling_gate_mutating_webhook.go
Labels: approved, lgtm, jira/valid-reference, tide/merge-method-squash

#569 Konflux: deprecated coverity-availability-check-oci-ta
  .tekton/multiarch-tuning-operator-build-pipeline.yaml
  .tekton/multiarch-tuning-operator-single-arch-build-pipeline.yaml
Labels: approved, lgtm

#571 Konflux: fbc fixes
  .tekton/fbc-pipeline.yaml
  .tekton/fbc-v4-16-pull-request.yaml
  .tekton/fbc-v4-16-push.yaml
  .tekton/fbc-v4-17-pull-request.yaml
  .tekton/fbc-v4-17-push.yaml
  .tekton/fbc-v4-18-pull-request.yaml
  .tekton/fbc-v4-18-push.yaml
  .tekton/fbc-v4-19-pull-request.yaml
  .tekton/fbc-v4-19-push.yaml
  Dockerfile
  fbc-v4-16/Dockerfile
  fbc-v4-18/Dockerfile
  fbc-v4-19/Dockerfile
Labels: approved, lgtm

#579 Konflux refrences update 1-0
  .tekton/multiarch-tuning-operator-build-pipeline.yaml
  .tekton/multiarch-tuning-operator-single-arch-build-pipeline.yaml
Labels: approved, lgtm

#578 Konflux: migration updates
  .tekton/multiarch-tuning-operator-build-pipeline.yaml
  .tekton/multiarch-tuning-operator-single-arch-build-pipeline.yaml
Labels: approved, lgtm

#582 Switched to using pipeline referenced from Tekton bundle on Quay.io
  .tekton/multiarch-tuning-operator-build-pipeline.yaml
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
  .tekton/multiarch-tuning-operator-single-arch-build-pipeline.yaml
Labels: approved, lgtm

#572 MULTIARCH-5351: Switched to using pipeline referenced from Tekton bundle on Quay.io
  .tekton/multiarch-tuning-operator-build-pipeline.yaml
  .tekton/multiarch-tuning-operator-bundle-pull-request.yaml
  .tekton/multiarch-tuning-operator-bundle-push.yaml
  .tekton/multiarch-tuning-operator-pull-request.yaml
  .tekton/multiarch-tuning-operator-push.yaml
  .tekton/multiarch-tuning-operator-single-arch-build-pipeline.yaml
Labels: approved, lgtm, jira/valid-reference

#566 MULTIARCH-5010: enoexec monitoring
  docs/enhancements/MTO-0004-enoexec-monitoring.md
  docs/enhancements/enoexec-monitoring-architecture.svg
Labels: approved, lgtm, jira/valid-reference
